config/routes.rb
Rails.application.routes.draw do
  resources :course_proposals
  resources :course_ideas
  resources :course_collections
  resources :pages
  resources :course_registrations
  resources :locations
  resources :course_sessions
  resources :courses 
  get "course_calendar/(:start_date)", to: "courses#calendar"
  get 'course_archive', to: "courses#index", :upcoming=>true
  namespace :admin do
    resources :users
    resources :course_proposals
    resources :course_proposal_questions
    resources :course_proposal_question_answers
    resources :course_ideas
    resources :courses
    resources :course_sessions
    resources :course_collections
    resources :locations
    resources :pages
    resources :menus
    resources :menu_pages
    resources :sites
    post 'course_proposals/:id/reject', to: "course_proposals#reject",:as => "reject_course_proposal_admin_course_proposal"
    post 'course_proposals/:id/defer', to: "course_proposals#defer",:as => "defer_course_proposal_admin_course_proposal"
    post 'course_proposals/:id/approve', to: "course_proposals#approve",:as => "approve_course_proposal_admin_course_proposal"

    
    root to: "courses#index"
  end
  resources :attachments
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  root :to => 'pages#homepage'

end

app/controllers/admin/courses_controller.rb
module Admin
  class CoursesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Course.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Course.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @upcoming=true
    if params[:upcoming]
      @upcoming=false 
      @courses = Course.all.where(:published=>true).find_all {|c| c.course_sessions.where("course_sessions.start >= ?",Date.today).length == 0} #TK limit by site
    else
      @courses = Course.all.where(:published=>true).joins(:course_sessions).where("course_sessions.start >= ?",Date.today)
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    authorize @course
  end

  def calendar
    @course_sessions=CourseSession.where(:approved=>true).joins(:course).where(:courses => { :published => true }) #TK limit by date, site
  end

  # GET /courses/new
#  def new
#   @course = Course.new
# end

# GET /courses/1/edit
#  def edit
#  end

  # POST /courses
  # POST /courses.json
#  def create
#    @course = Course.new(course_params)

#    respond_to do |format|
#      if @course.save
#        format.html { redirect_to @course, notice: 'Course was successfully created.' }
#        format.json { render :show, status: :created, location: @course }
#      else
#        format.html { render :new }
#        format.json { render json: @course.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
#  def update
#    respond_to do |format|
#      if @course.update(course_params)
#        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
#        format.json { render :show, status: :ok, location: @course }
#      else
#        format.html { render :edit }
#        format.json { render json: @course.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  # DELETE /courses/1
  # DELETE /courses/1.json
#  def destroy
#   @course.destroy
#    respond_to do |format|
#      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
#      format.json { head :no_content }
#    end
#  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :very_short_description, :full_description, :location_id, :instructor_id, :homesite_id,:limit)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_coursecards.html.erb
  <% courses.each_slice(3) do |group| %>
  <div class="row row-eq-height">
    <% group.each do |course| %>
    <div class="col-sm-6 col-lg-4 mt-3">
      <div class="card">
	<div class="card-block">
          <h4><%= link_to course.name,course %></h4>
          <p class="lead"><%= course.very_short_description %></p>
          <h6><%= link_to course.location.name,course.location %></h6>
	  <% course.course_sessions.where(:approved=>true).order(:start).each do |cs| %>
	  <div class="small"><%= cs.start.to_formatted_s(:starttime) %> - <%= cs.end.to_formatted_s(:endtime) %> </div>
	  <% end %>
	  <div class="course_actions">
	    <%= link_to "More info",course,class: "btn btn-info btn-block mt-1 mb-1 btn-sm" %>
	    <% if current_user && (current_user.courses_registered_for.include? course) %>
	      <%= link_to "Cancel your registration for this course",current_user.course_registrations.where(:course=>course).first, method: :delete, class: "btn btn-outline-warning btn-block" %>
	    <% elsif course.registration_open? %>
	      <%= form_for(CourseRegistration.new(:course=>course)) do |f| %>
	        <%= f.hidden_field :course_id %>
	        <%= f.submit "Register for this course",class: "btn btn-sm btn-primary btn-block" %>
	      <% end %>
	    <% else %>
	      <div class="btn btn-outline-secondary btn-block">Course is full</div>
	    <% end %>
	  </div>

	</div>
	</div>
    </div>
    <% end %>
  </div>
  <% end %>

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :very_short_description %>
    <%= f.text_area :very_short_description %>
  </div>

  <div class="field">
    <%= f.label :full_description %>
    <%= f.text_area :full_description %>
  </div>

  <div class="field">
    <%= f.label :location_id %>
    <%= f.text_field :location_id %>
  </div>

  <div class="field">
    <%= f.label :instructor_id %>
    <%= f.text_field :instructor_id %>
  </div>

  <div class="field">
    <%= f.label :homesite_id %>
    <%= f.text_field :homesite_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/calendar.html.erb
<div class="monthcalendar">
<%= month_calendar(attribute: :start, end_attribute: :end,events: @course_sessions) do |date,course_sessions| %>
<div class="daynumber"><%= date.day %></div>
<% course_sessions.each do |course_session| %>
<div>
  <%= link_to course_session.course.name,course_session.course %>
  <div class="small"><%= course_session.start.to_formatted_s(:starttimeonly) %> - <%= course_session.end.to_formatted_s(:endtime) %> </div>
</div>
<% end %>
<% end %>
</div>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1><%= @upcoming ? "Upcoming" : "Past" %> Courses</h1>
<div class="mb-3"><%= link_to 'Propose a course!', new_course_proposal_path, :class=>"btn btn-primary btn-block" %></div>

<div class="courses">
  <%= render "coursecards", {:courses=>@courses} %>
</div>
<br>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<h1>
  <%= @course.name %> 
  <% unless @course.published? %><span class="badge badge-warning">Not published</span> <% end %>
  <% if current_user && @course.instructor==current_user %><span class="badge badge-success">I'm teaching this!</span> <% end %>
  <% if current_user && (current_user.courses_registered_for.include? @course) %><span class="badge badge-success">I'm taking this!</span> <% end %>
</h1>
<p class="lead">
  <%= @course.very_short_description %>
</p>

<div class="card card-outline-secondary mb-3 ">
  <div class="card-block">
    <dl class="row">
      <dt class="col-sm-2">Location</dt>
      <dd class="col-sm-10"><%= link_to @course.location.name, @course.location %></dd>
      <dt class="col-sm-2">Instructor</dt>
      <dd class="col-sm-10"><%= @course.instructor.name %></dd>
      <% if @course.course_collections.where(:is_published  => true).length > 0 %>
      <dt class="col-sm-2">Part of</dt>
      <dd class="col-sm-10">
	<% @course.course_collections.where(:is_published  => true).each do |cc| %>
	<%= link_to cc.name,cc,:class => "badge badge-pill badge-default"%>
	<% end %>
      </dd>
      <% end %>
      <dt class="col-sm-2">Sessions</dt>
      <dd class="col-sm-10">
	<% @course.course_sessions.where(:approved=>true).order(:start).each do |cs| %>
	<div><%= cs.start.to_formatted_s(:starttime) %> - <%= cs.end.to_formatted_s(:endtime) %> </div>
	
	<% end %>
      </dd>
       <% if current_user && (@course.instructor==current_user || current_user.admin?) %>
      <dt class="col-sm-2">Learners</dt>
      <dd class="col-sm-10">
	<table class="table table-sm">
	  <tr><th>Name</th><th>Email</th></tr>
	  <% @course.learners.each do |x| %>
	  <tr>
	    <td><%= x.name %></td>
	    <td><%= x.email %></td>
	  </tr>
	  <% end %>
	</table>
      </dd>
      <% end %>
    </dl>
  </div>
</div>

<div class="m-b-3"> 
<% if current_user && (current_user.courses_registered_for.include? @course) %>
  <%= link_to "Cancel your registration for this course",current_user.course_registrations.where(:course=>@course).first, method: :delete, class: "btn btn-outline-warning btn-block" %>
<% elsif @course.registration_open? %>
  <%= form_for(CourseRegistration.new(:course=>@course)) do |f| %>
    <%= f.hidden_field :course_id %>
    <%= f.submit "Register for this course",class: "btn btn-outline-primary btn-block" %>
  <% end %>
<% else %>
<div class="btn btn-outline-secondary btn-block">Course is full</div>

<% end %>
  &nbsp;
</div>

<div class="sharethis-inline-share-buttons"></div>
<div class="m-b-3">&nbsp;</div>

<%= render @course.full_description %>

<% content_for :title do %>
<%= @site.name %>: <%= @course.name %>
<% end %>

<% content_for :description do %>
  <%= @course.very_short_description %>
<% end %>